56-corrigir-estilização-dos-componentes
lucaoskaique/entregacao-app pull request #58
Opened 2024-05-17 21:16 UTC by VFGarciaDev

Corrigir estilização dos componentes

2024-05-17 23:04 UTC, lucaoskaique requested changes
## Tenho duas alterações

- [ ] O grid ta quase certo, só acertar o footer
![image](https://github.com/lucaoskaique/entregacao-app/assets/20323741/b37bcd0c-d65f-4e73-9bea-74e24a7ddcbd)


- [ ] o preto do navbar ta muito preto escondendo o icone de texto, peguem as cores do figma certinha e da uma revisada no projeto

![image](https://github.com/lucaoskaique/entregacao-app/assets/20323741/bbf860bc-ed30-4e62-a76c-70ebdb0c961e)

2024-05-17 23:56 UTC, VFGarciaDev commented
Não foi realizado a correção da cor do título ao trocar de tema, visto que a opção de poder trocar o tema será removida

2024-05-18 21:07 UTC, lucaoskaique requested changes

2024-05-18 21:07 UTC, lucaoskaique commented on src/components/ui/container.tsx
Esse component nao é necessario,com  o uso de container do typescript nao precisa ser criado

2024-05-18 21:07 UTC, lucaoskaique commented on src/components/ui/hero.tsx
>  import { Container } from './container';
Desnecessario esse component se ja usamos o container do tailwind

2024-05-18 21:07 UTC, lucaoskaique commented on tailwind.config.js
> +      padding: "20px",
Porque mudou pra px?

2024-05-18 23:15 UTC, VFGarciaDev commented on src/components/ui/hero.tsx
>  import { Container } from './container';
Esse component já tinha sido adicionado antes, não criei ele

2024-05-18 23:15 UTC, VFGarciaDev commented on src/components/ui/container.tsx
Esse component já tinha sido adicionado antes, não criei ele

2024-05-18 23:16 UTC, VFGarciaDev commented on index.html
Perdão, quando fiz o commit, não tinha essa pasta ainda. Vou corrigir

2024-05-20 13:22 UTC, closed without merging